const foodDishes = [
  {
    id: 1,
    name: "Spaghetti Carbonara",
    description: "Creamy pasta with a smoky bacon twist.",
    price: 12.99,
    quantity: 1,
  },
  {
    id: 2,
    name: "Margherita Pizza",
    description: "Classic pizza with fresh tomatoes, basil, and mozzarella.",
    price: 10.49,
    quantity: 1,
  },
  {
    id: 3,
    name: "Caesar Salad",
    description: "Crisp romaine with tangy Caesar dressing and croutons.",
    price: 8.99,
    quantity: 1,
  },
  {
    id: 4,
    name: "Beef Tacos",
    description: "Juicy beef topped with fresh salsa and avocado.",
    price: 9.99,
    quantity: 1,
  },
  {
    id: 5,
    name: "Chicken Alfredo",
    description: "Rich and creamy pasta with tender grilled chicken.",
    price: 13.49,
    quantity: 1,
  },
  {
    id: 6,
    name: "Vegetable Stir-Fry",
    description: "Colorful veggies sautéed in a savory sauce.",
    price: 11.29,
    quantity: 1,
  },
  {
    id: 7,
    name: "Cheeseburger",
    description: "Grilled to perfection with melted cheddar cheese.",
    price: 10.99,
    quantity: 1,
  },
  {
    id: 8,
    name: "Sushi Platter",
    description: "A delightful assortment of fresh sushi rolls.",
    price: 14.99,
    quantity: 1,
  },
  {
    id: 9,
    name: "Grilled Salmon",
    description: "Perfectly grilled salmon with a lemon-butter glaze.",
    price: 15.99,
    quantity: 1,
  },
  {
    id: 10,
    name: "BBQ Ribs",
    description: "Tender ribs smothered in a smoky BBQ sauce.",
    price: 16.49,
    quantity: 1,
  },
  {
    id: 11,
    name: "Greek Salad",
    description:
      "Fresh veggies, feta cheese, and olives with a zesty dressing.",
    price: 9.49,
    quantity: 1,
  },
  {
    id: 12,
    name: "Lobster Bisque",
    description: "Rich and creamy soup with succulent lobster.",
    price: 11.99,
    quantity: 1,
  },
  {
    id: 13,
    name: "Eggplant Parmesan",
    description: "Layers of eggplant, marinara, and melted cheese.",
    price: 12.29,
    quantity: 1,
  },
  {
    id: 14,
    name: "Chicken Tikka Masala",
    description: "Spicy and creamy curry with tender chicken pieces.",
    price: 13.99,
    quantity: 1,
  },
  {
    id: 15,
    name: "Pad Thai",
    description: "Stir-fried noodles with shrimp, tofu, and peanuts.",
    price: 11.49,
    quantity: 1,
  },
];

export default foodDishes;
